### ISSUE TITLE
The delete keyword is shown in distinct colors (unexpected).

### ISSUE THREAD

**Issue by hcoona** [ifplusor/lunaria#1]
![image](https://user-images.githubusercontent.com/712433/140455090-95a4814f-7ed0-4cd3-beb7-89f420442647.png)

**Comment by ifplusor** [comment]
@hcoona Please post the detail for tokens and scopes.
![image](https://user-images.githubusercontent.com/9999114/140455352-b1620fc2-202c-4966-ac5c-5723191713c6.png)

**Comment by hcoona** [comment]
![image](https://user-images.githubusercontent.com/712433/140455987-8011f02c-66bf-4f44-a04c-a4169531c682.png)

**Comment by hcoona** [comment]
![image](https://user-images.githubusercontent.com/712433/140456130-6661c64f-f2d6-452d-863c-b34d1042c872.png)

**Comment by hcoona** [comment]
close due to VSCode textmate scopes cannot distinguish operator delete keyword & memory delete keyword.
