### ISSUE TITLE
final keyword on class is not colored.

### ISSUE THREAD

**Issue by hcoona** [ifplusor/lunaria#2]
![image](https://user-images.githubusercontent.com/712433/140455810-9e1bb183-121c-4117-bb43-89239e562587.png)

**Comment by hcoona** [comment]
![image](https://user-images.githubusercontent.com/712433/140456017-3b87f2f6-25cf-4ebf-a981-82a93116cc66.png)

**Comment by ifplusor** [comment]
Can not capture it with textmate scopes.
